spring.application.name=blog

spring.profiles.include=local

<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=create
=======
spring.jpa.hibernate.ddl-auto=update
>>>>>>> 24598e479ed8c5deaa00832f510ef8e0ddd67fd1
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true